### ISSUE TITLE
请问这个逆解cpp程序能否在matlab里面用？谢谢！

### ISSUE THREAD

**Issue by carry-xz** [pyni/ur_kinematics#1]

**Comment by pyni** [comment]
你好！
这是一个C++工程
如果要用也可以，C++和matlab具有联合编译的功能，但比较复杂，且你需要该这个项目的代码把接口调出来以方便matlab叫用。
解析解的目的本来就是为了快，写成C++的目的其实也是为了快
所以个人感觉没有必要用matlab
祝好！
