### ISSUE TITLE
X与Y是不是反向了？

### ISSUE THREAD

**Issue by yjbryant** [pyni/ur_kinematics#2]
用这段代码计算出的数据，跟真实的机器人对比，发现X，Y方向正好反了，我用的是UR3

**Comment by pyni** [comment]
你好，我这个项目是针对UR5的
请问你用的是ur官方提供的UR模型么

**Comment by yjbryant** [comment]
我看代码里面有UR3的一些参数宏定义，所以就把UR5和UR10的参数注销了，用来计算UR3的正逆解了
我手里有个UR3
用（0，0，1，0，1，0）计算出来的正解跟实际机器人上显示数值，正好X ,Y 向反了

**Comment by yjbryant** [comment]
我没有用ROS，直接把正逆解部分代码取出来，用C++编码的

**Comment by pyni** [comment]
#ifdef UR3_PARAMS
    const double d1 =  0.1519;
    const double a2 = -0.24365;
    const double a3 = -0.21325;
    const double d4 =  0.11235;
    const double d5 =  0.08535;
    const double d6 =  0.0819;
    #endif
那可以先核对一下，你的模型和这个参数模型是不是一样
我当时用的是UR官方提供的模型

**Comment by yjbryant** [comment]
你是机动的吧，我github账号就是微信，加一个？明天我上午去找你讨论下？

**Comment by pyni** [comment]
行呀，不过这个项目有点久远，我可能记不太清了

**Comment by yjbryant** [comment]
没事，请教一下，我比较新手
